---
- name: Patch Red Hat servers and update Apache if installed
  hosts: all
  become: yes
  tasks:
    - name: Update all packages to the latest version
      yum:
        name: '*'
        state: latest

   

    - name: Update Apache if installed
      yum:
        name: httpd
        state: latest
      

   
   
